---
grails:
    profile: web
    codegen:
        defaultPackage: yjytc
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    config:
        locations: ["classpath:app.groovy"]
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        fillDelayDays: 90   # 可以延时填写的天数
spring:
    application:
        name: '任务台账系统'
#    cloud:
#        inetutils:
#            preferredNetworks[0]: ^192\.168
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: true
    jmx:
        enabled: true
eureka:
    instance:
        prefer-ip-address: true
        instance-id: '台账微服务'
    client:
#        fetchRegistry: false
        serviceUrl:
            defaultZone: http://10.0.112.14:8761/eureka,http://10.0.112.20:1111/eureka/
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
        json:
            compileStatic: false
            generator:
                dateFormat: "yyyy-MM-dd HH:mm:ss"
                locale: "zh/CN"
                timeZone: "GMT+8"
endpoints:
    #enabled: true
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    driverClassName: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/big19?characterEncoding=UTF-8" #useUnicode=true&
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

environments:
    development:
        dataSource:
            username: "root"
            password: ""
            dbCreate: update
            logSql: false
    test:
        dataSource:
            username: "root"
            password: ""
            dbCreate: create-drop
            logSql: true
    production:
        dataSource:
            username: "root"
            password: "Plngj1anG!_"
            dbCreate: none
            logSql: false
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 10 * 60000
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 3600000
                numTestsPerEvictionRun: 3
                validationQuery: "select 1"
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                jdbcInterceptors: "ConnectionState"
                defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
